### ISSUE TITLE
NullPointerException, fails to connect to servers?

### ISSUE THREAD

**Issue by svdragster** [dommi2212/BungeeBridge#1]
22:19:55 [SEVERE] Exception in thread "Thread-142"
22:19:55 [SEVERE] java.lang.NullPointerException
22:19:55 [SEVERE]     at me.dommi2212.BungeeBridge.PacketHandler.handlePacket(PacketHandler.java:230)
22:19:55 [SEVERE]     at me.dommi2212.BungeeBridge.ClientRunnable.run(ClientRunnable.java:42)
22:19:55 [SEVERE]     at java.lang.Thread.run(Thread.java:745)

Happens after reloading the Bungee Plugin.
After reloading the Clients on the servers it stops spamming the error above.

**Comment by dommi2212** [comment]
This issue was already reported and will be fixed in the next days.
Anyway thanks for reporting!
Please stay patient until it's fixes.

**Comment by dommi2212** [comment]
Fixed bug in version 1.6.1:
https://github.com/dommi2212/BungeeBridge/commit/e3db44652ae55b6e86f608db28875245e7956e9e
